# Generated by Django 3.2.3 on 2021-05-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='tables/excels/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='tables/covers/')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
