# Generated by Django 3.2.3 on 2021-05-21 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input_tables', '0002_auto_20210521_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='pdf',
            new_name='excel',
        ),
    ]
