# Generated by Django 3.2.3 on 2021-05-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input_tables', '0004_auto_20210521_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='excel_to_table_image',
        ),
        migrations.RemoveField(
            model_name='table',
            name='title',
        ),
    ]
